#!/bin/bash

declare -a cydia
cydia=($CYDIA)

if [[ ${CYDIA+@} ]]; then
    eval "echo 'finish:restart' >&${cydia[0]}"
else
    echo -n -e "will Respring in 3s"
    sleep 1
    echo -n -e "\rwill Respring in 2s"
    sleep 1;
    echo -e "\rwill Respring in 1s  !!!"
    echo -e "\nReady !!?"
    sleep 1;
    killall -9 SpringBoard 
fi

#end script