SDKVERSION = 5.0
include theos/makefiles/common.mk

BUNDLE_NAME = KillBackgroundPreferences
KillBackgroundPreferences_FILES = KillBackgroundPreferences.mm
KillBackgroundPreferences_INSTALL_PATH = /Library/PreferenceBundles
KillBackgroundPreferences_FRAMEWORKS = UIKit
KillBackgroundPreferences_PRIVATE_FRAMEWORKS = Preferences

include theos/makefiles/bundle.mk
